config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "kakeibos#index"
    resources :expenses, only: [:index, :new, :create, :show, :destroy, :edit, :update]
    resources :plans, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :analysis, only: [:index]
    resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '食費' },
    { id: 3, name: '家賃、光熱費、通信費' },
    { id: 4, name: '交通費' },
    { id: 5, name: '自己投資' },
    { id: 6, name: '保険、投資信託' },
    { id: 7, name: '趣味、遊び' },
    { id: 8, name: '嗜好品' },
    { id: 9, name: 'その他' },
  ]
end

app/models/expense.rb
class Expense < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :payment


  belongs_to :user

  
  validates :start_time, :name, :wheretobuy, :category, :payment, presence: true
  validates :category_id, :payment_id, numericality: { other_than: 1 } 

  with_options presence: true, format: { with: /\A[0-9]+\d\z/, message: '半角数字で入力してください' } do
    validates :price
  end


end

app/models/payment.rb
class Payment < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '現金' },
    { id: 3, name: '口座振替' },
    { id: 4, name: 'クレジットカード' },
    { id: 5, name: '電子マネー' },
    { id: 6, name: 'その他' },

  ]
end

app/models/plan.rb
class Plan < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :payment


  belongs_to :user


  validates :start_time, :name, :payment, presence: true
  validates :payment_id, numericality: { other_than: 1 } 

  with_options presence: true, format: { with: /\A[0-9]+\d\z/, message: '半角数字で入力してください' } do
    validates :price
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :expenses
         has_many :plans


  validates :nickname, :name, :password,presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]{6,}+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください' 
end

app/controllers/analysis_controller.rb
class AnalysisController < ApplicationController

  def index
    @expenses = current_user.expenses.all
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth if Rails.env.production?
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
 
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :name])
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def index
    @q = current_user.expenses.ransack(params[:q])
    @expenses = @q.result(distinct: true).page(params[:page]).per(10).order("created_at DESC")
  end


  def new
    @expense = Expense.new
  end

  def create
    @expense =Expense.new(expense_params)

    if @expense.valid?
      @expense.save
      redirect_to root_path
    else
      render 'new'
    end
    
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def update
    @expense = Expense.find(params[:id])
    @expense.update(expense_params)
    redirect_to root_path
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    redirect_to root_path
  end

  def show
    @expense = Expense.find(params[:id])
  end

  private
  def expense_params
    params.require(:expense).permit(:start_time, :name, :price, :wheretobuy, :category_id, :payment_id, :memo).merge(user_id: current_user.id)
  end

end

app/controllers/kakeibos_controller.rb
class KakeibosController < ApplicationController

  def index
    @expenses = current_user.expenses.all
    @plans = current_user.plans.all
  end


end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @expenses = current_user.expenses.all.order("created_at DESC")
    @plans = current_user.plans.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)

    if @plan.valid?
      @plan.save
      redirect_to root_path
    else
      render 'new'
    end

  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    @plan.update(plan_params)
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    redirect_to plans_path 
  
  end



  private
  def plan_params
    params.require(:plan).permit(:start_time, :name, :price, :payment_id, :memo).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end

end

app/helpers/analysis_helper.rb
module AnalysisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/kakeibos_helper.rb
module KakeibosHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/analysis/index.html.erb
分析ページ
<html lang="ja">

<body>
  <h1>円グラフ</h1>
  <canvas id="myPieChart"></canvas>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

  <script>
  var ctx = document.getElementById("myPieChart");
  var myPieChart = new Chart(ctx, {
    type: 'pie',
    data: {
      labels: ["A型", "O型", "B型", "AB型"],
      datasets: [{
          backgroundColor: [
              "#BB5179",
              "#FAFF67",
              "#58A27C",
              "#3C00FF"
          ],
          data: [38, 31, 21, 10]
      }]
    },
    options: {
      title: {
        display: true,
        text: '血液型 割合'
      }
    }
  });
  </script>
</body>
</html>

app/views/expenses/_main_top.html.erb
<div class="main-header">
  <div class="left-header">
      <div class="main-header-title">
        <%=link_to '出費管理アプリ', root_path, class:"header-logo-link" %>
          ----出費履歴----
      </div>
  </div>

  <div class="right-header">
      <div class="main-header-logout">
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "post" %>
      </div>
  </div>
</div>

<div class="top-screen">

  <div class="top-list" id="show-top-list">
    <div class="top-list-all">
      <div class="search_list">
        <%= search_form_for @q do |f| %>
        <div class="search_list_top">
          <div class="search_keyworrd">
             <%= f.label :name_or_wheretobuy_or_memo, "キーワード" %>
             <%= f.search_field :name_or_wheretobuy_or_memo_cont %>
          </div>
        
          <div class="search_date">
              <%= f.label :start_time,"日付" %>
              <%= f.date_select :start_time_gteq, include_blank: '-' %>日〜
              <%= f.date_select :start_time_lteq, include_blank: '-' %>日
          </div>
       </div>
        <div class="search_payment">
            <%= f.label :payment_id,"支払い方法" %>
            <%= f.radio_button :payment_id_eq, '', {:checked => true} %>指定なし
            <%= f.radio_button :payment_id_eq, 2 %>現金
            <%= f.radio_button :payment_id_eq, 3 %>口座振替
            <%= f.radio_button :payment_id_eq, 4 %>クレジットカード
            <%= f.radio_button :payment_id_eq, 5 %>電子マネー
            <%= f.radio_button :payment_id_eq, 6 %>その他
        </div>


        <div class="seach" id="seach">
            <%= f.submit "検索" %>
             <%=link_to 'リセット', expenses_path %>
        </div>
      </div>

      <table class="top-list-table">
          <thead>
              <tr>
                 <th>詳細</th>
                 <th><%= sort_link(@q, :start_time, "日付") %></th>
                 <th><%= sort_link(@q, :name, "名前") %></th>
                 <th>金額</th>
                 <th>購入場所</th>
                 <th>カテゴリー</th>
                 <th>支払い方法</th>
               </tr>
           </thead>

          <tbody>
          <% @expenses.each do |expense| %>
            <tr>
              <td><%= link_to "詳細", expense_path(expense.id), class: "post" %></td>
              <td><%= expense.start_time.strftime("%m/%d") %></td>
              <td><%= expense.name %></td>
              <td>¥<%= expense.price %></td>
              <td><%= expense.wheretobuy %></td>
              <td><%= expense.category.name %></td>
              <td><%= expense.payment.name %></td>
             </tr>
             <% end %>
          <% end %>
           
          </tbody>
      </table>
      <%= paginate @expenses %> 
    </div>

  </div>


</div>

app/views/expenses/_side_bar.html.erb
<%# サイドバーのheader %>
<div class="side-bar-header">
  <div class="header-logo">
    <%= current_user.nickname %>
  </div>
</div>

  
<%# サイドバーのリスト %>
<div class="link-lists">
  <div class="link-lists-1">
    <div class="link-lists-name">入力リスト</div>
      <ul>
        <li class="show" ><%= link_to "出費を入力", new_expense_path, class: "post" %> </li>
        <li class="show" ><%= link_to "予定を入力", new_plan_path, class: "post" %> </li>
      </ul>
  </div>

  <div class="link-lists-2">
    <div class="link-lists-name">表示リスト</div>
      <ul>
        <li class="show" ><%= link_to "トップページ", root_path, class: "post" %> </li>
        <li class="show" ><%= link_to "カレンダー", plans_path, class: "post" %> </li>
        <li class="show" ><%= link_to "出費履歴", expenses_path, class: "post" %> </li>
        <%# <li class="show" ><%= link_to "分析", analysis_index_path, class: "post" %> </li> 
      </ul>
    </div>
</div>

app/views/expenses/edit.html.erb
<div class="edit-expense">
  <div class="edit-expense-form">
    <div class="edit-expense-top">
      出費内容を変更する
    </div>

      <div class="edit-expense-body">
        <%= form_with model:@expense, local: true do |f| %>

          <div class="edit-expense-body-name">支払日</div>
          <%= f.date_select :start_time, id:"expense-day" %>

          <div class="edit-expense-body-name">品物</div>
          <%= f.text_area :name, class:"expense-text", id:"expense-name", placeholder:"購入した物（必須 40文字まで)", maxlength:"40" %>

          <div class="edit-expense-body-name">金額</div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"expense-price", placeholder:"例）300" %>

          <div class="edit-expense-body-name">購入場所</div>
          <%= f.text_area :wheretobuy, class:"expense-text", id:"expense-wheretobuy", placeholder:"購入した場所（必須 40文字まで)", maxlength:"40" %>

          <div class="edit-expense-body-name">項目</div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"expense-category"}) %>

          <div class="edit-expense-body-name">支払い方法</div>
          <%= f.collection_select(:payment_id, Payment.all, :id, :name, {}, {class:"select-box", id:"expense-payment"}) %>

          <div class="edit-expense-body-name">メモ</div>
          <%= f.text_area :memo, class:"expense-text", id:"expense-memo" %>
 
          <div class="sell-btn-contents">
            <%= f.submit "変更する" ,class:"sell-btn" %>
            <%=link_to 'もどる', root_path, class:"back-btn" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/expenses/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>

  <div class="main-top">
    <%= render "main_top" %>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="new-expense">
  <div class="new-expense-form">
    <div class="new-expense-top">
      新規出費を登録する
    </div>

      <div class="new-expense-body">
        <%= form_with model: @expense, local: true do |f| %>
         <%= render 'layouts/error_messages', model: f.object %>

          <div class="new-expense-body-name">支払日</div>
          <%= f.date_select :start_time, id:"expense-day" %>

          <div class="new-expense-body-name">品物</div>
          <%= f.text_area :name, class:"expense-text", id:"expense-name", placeholder:"必須：購入した物", maxlength:"40" %>

         <div class="new-expense-body-name">金額</div>
         <span class="sell-yen">¥</span>
         <%= f.text_field :price, class:"price-input", id:"expense-price", placeholder:"必須：半角数字で入力してください" %>

          <div class="new-expense-body-name">購入場所</div>
          <%= f.text_area :wheretobuy, class:"expense-text", id:"expense-wheretobuy", placeholder:"必須：購入した場所", maxlength:"40" %>

          <div class="new-expense-body-name">項目</div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"expense-category"}) %>

          <div class="new-expense-body-name">支払い方法</div>
          <%= f.collection_select(:payment_id, Payment.all, :id, :name, {}, {class:"select-box", id:"expense-payment"}) %>

          <div class="new-expense-body-name">メモ</div>
          <%= f.text_area :memo, class:"expense-text", id:"expense-memo" %>
 

          <div class="sell-btn-contents">
              <%= f.submit "登録する" ,class:"button-type1" %>
              <%=link_to 'もどる', root_path, class:"back-btn" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/expenses/show.html.erb
<div class="show-expense">
  <div class="show-expense-form">

    <div class="show-expense-top">
      詳細表示
    </div>

    <div class="show-expense-body">
      <div class="show-expense-body-name">名前</div>
      <%= @expense.name %>

      <div class="show-expense-body-name">支払日</div>
      <%=@expense.start_time %>

      <div class="show-expense-body-name">支払場所</div>
      <%=@expense.wheretobuy %>

      <div class="show-expense-body-name">支払金額</div>
      ¥<%=@expense.price %>

      <div class="show-expense-body-name">支払い方法</div>
      <%=@expense.payment.name %>

      <div class="show-expense-body-name">項目</div>
      <%=@expense.category.name %>

      <div class="show-expense-body-name">メモ</div>
      <%=@expense.memo %>


      <div class="sell-btn-contents">
        <%= link_to '内容の編集', edit_expense_path {expense.id}, method: :get, class: "expense-red-btn" %>
        <%= link_to '削除', expense_path {expense.id}, method: :delete, class:'expense-destroy' %>
      </div>
    </div>
  </div>
</div>

app/views/kakeibos/_main_top.html.erb
<div class="main-header">
  <div class="left-header">
      <div class="main-header-title">
        <%=link_to '出費管理アプリ', root_path, class:"header-logo-link" %>
          ----トップページ----
      </div>
  </div>

  <div class="right-header">
      <div class="main-header-logout">
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "post" %>
      </div>
  </div>
</div>

<div class="top-screen">

    <div class="top-info">

    <div class="top-info-left">
        <div class="top-info-title">昨日</div>
        <div class="top-info-left-body">
          <div class="top-info-left-body1">
            <%= current_user.expenses.where(start_time: Date.yesterday).sum(:price) %>円出費しました
          </div>
          <div class="top-info-left-body1">
            出費を見直しましょう！！
          </div>
        </div>
      </div>

      <div class="top-info-left">
        <div class="top-info-title">今日</div>
        <div class="top-info-left-body">
          <div class="top-info-left-body1">
            <%= current_user.expenses.where(start_time: Date.today).sum(:price) %>円出費しました
          </div>
          <div class="top-info-left-body1">
            <%= current_user.plans.where(start_time: Date.today).sum(:price) %>円出費予定があります
          </div>
        </div>
      </div>

      <div class="top-info-right">
        <div class="top-info-title">明日</div>
        <div class="top-info-right-body">
          <div class="top-info-left-body1">
            <%= current_user.plans.where(start_time: Date.tomorrow).sum(:price) %>円出費予定です
          </div>
          <div class="top-info-left-body1">
            口座の残高を確認しましょう！
          </div>
        </div>
      </div>
    </div>
    
   <table class="top-list-table">
   <h2>最新の出費履歴</h2>
          <thead>
              <tr>
                 <th>詳細</th>
                 <th>日付</th>
                 <th>名前</th>
                 <th>金額</th>
                 <th>購入場所</th>
                 <th>カテゴリー</th>
                 <th>支払い方法</th>
               </tr>
           </thead>

         <tbody>
          <% @expenses.last(3).each do |expense| %>
            <tr>
              <td><%= link_to "詳細", expense_path(expense.id), class: "post" %></td>
              <td><%= expense.start_time.strftime("%m/%d") %></td>
              <td><%= expense.name %></td>
              <td>¥<%= expense.price %></td>
              <td><%= expense.wheretobuy %></td>
              <td><%= expense.category.name %></td>
              <td><%= expense.payment.name %></td>
             </tr>            
          <% end %>
           
          </tbody>
      </table>
 </table>

  <table class="top-list-table">
   <h2>最新の出費予定履歴</h2>
          <thead>
              <tr>
                 <th>詳細</th>
                 <th>日付</th>
                 <th>名前</th>
                 <th>金額</th>
                 <th>支払い方法</th>
               </tr>
           </thead>

         <tbody>
          <% @plans.last(3).each do |plan| %>
            <tr>
            <td><%= link_to "詳細", edit_plan_path(plan.id), class: "get" %></td>
              <td><%= plan.start_time.strftime("%m/%d") %></td>
              <td><%= plan.name %></td>
              <td>¥<%= plan.price %></td>
              <td><%= plan.payment.name %></td>
             </tr>            
          <% end %>
           
          </tbody>
      </table>
  </table>



</div>

app/views/kakeibos/_side_bar.html.erb
<%# サイドバーのheader %>
<div class="side-bar-header">
  <div class="header-logo">
    <%= current_user.nickname %>
  </div>
</div>

  
<%# サイドバーのリスト %>
<div class="link-lists">
  <div class="link-lists-1">
    <div class="link-lists-name">入力リスト</div>
      <ul>
        <li class="show" ><%= link_to "出費を入力", new_expense_path, class: "post" %> </li>
        <li class="show" ><%= link_to "予定を入力", new_plan_path, class: "post" %> </li>
      </ul>
  </div>

  <div class="link-lists-2">
    <div class="link-lists-name">表示リスト</div>
      <ul>
        <li class="show" ><%= link_to "トップページ", root_path, class: "post" %> </li>
        <li class="show" ><%= link_to "カレンダー", plans_path, class: "post" %> </li>
        <li class="show" ><%= link_to "出費履歴", expenses_path, class: "post" %> </li>
          <%# <li class="show" ><%= link_to "分析", analysis_index_path, class: "post" </li>  %>
      </ul>
    </div>
</div>

app/views/kakeibos/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>

  <div class="main-top">
    <%= render "main_top" %>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakeibo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/_main_top.html.erb
<div class="main-header">
  <div class="left-header">
      <div class="main-header-title">
        <%=link_to '出費管理アプリ', root_path, class:"header-logo-link" %>
          ----カレンダー----
      </div>
  </div>

  <div class="right-header">
      <div class="main-header-logout">
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "post" %>
      </div>
  </div>
</div>

<div class="top-screen">

  <div class="top-calender" id="show-top-calender">
       <%= month_calendar events: @plans do |date, plans| %>
         <%= date.day %>
         <div class = "clennder-expenses">
           <% if current_user.expenses.where(start_time: date).sum(:price) > 0%>
             <div>
                <%= current_user.expenses.where(start_time: date).sum(:price) %>円出費
             </div>
           <% end %>
         </div>

         <div class = "calender-plans">
           <% plans.each do |plan| %>
             <div class = "calender-plan">
               <%= link_to "✅", edit_plan_path(plan.id), class: "get" %>
             </div>
           <% end %>

           <% if current_user.plans.where(start_time: date).sum(:price) > 0%>
             <div>
                <%= current_user.plans.where(start_time: date).sum(:price) %>円出費予定
             </div>
           <% end %>
         </div>


        <% end %>
   </div>




</div>

app/views/plans/_side_bar.html.erb
<%# サイドバーのheader %>
<div class="side-bar-header">
  <div class="header-logo">
    <%= current_user.nickname %>
  </div>
</div>

  
<%# サイドバーのリスト %>
<div class="link-lists">
  <div class="link-lists-1">
    <div class="link-lists-name">入力リスト</div>
      <ul>
        <li class="show" ><%= link_to "出費を入力", new_expense_path, class: "post" %> </li>
        <li class="show" ><%= link_to "予定を入力", new_plan_path, class: "post" %> </li>
      </ul>
  </div>

  <div class="link-lists-2">
    <div class="link-lists-name">表示リスト</div>
      <ul>
        <li class="show" ><%= link_to "トップページ", root_path, class: "post" %> </li>
        <li class="show" ><%= link_to "カレンダー", plans_path, class: "post" %> </li>
        <li class="show" ><%= link_to "出費履歴", expenses_path, class: "post" %> </li>
        <%# <li class="show" ><%= link_to "分析", analysis_index_path, class: "post" </li>  %>
      </ul>
    </div>
</div>

app/views/plans/edit.html.erb
<div class="edit-expense">
  <div class="edit-expense-form">
    <div class="edit-expense-top">
      出費予定の確認・変更
    </div>

      <div class="edit-expense-body">
        <%= form_with model:@plan, local: true do |f| %>

          <div class="edit-expense-body-name">支払日</div>
          <%= f.date_select :start_time, id:"plan-day" %>

          <div class="edit-expense-body-name">名前</div>
          <%= f.text_area :name, class:"expense-text", id:"plan-name", placeholder:"購入した物（必須 40文字まで)", maxlength:"40" %>

          <div class="edit-expense-body-name">金額</div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"plan-price", placeholder:"例）300" %>

          <div class="edit-expense-body-name">支払い方法</div>
          <%= f.collection_select(:payment_id, Payment.all, :id, :name, {}, {class:"select-box", id:"plan-payment"}) %>

          <div class="edit-expense-body-name">メモ</div>
          <%= f.text_area :memo, class:"expense-text", id:"plan-memo" %>
 
          <div class="sell-btn-contents">
            <%= f.submit "変更する" ,class:"button-type1" %>
            <%= link_to '削除', plan_path {plan.id}, method: :delete, class:'plan-destroy' %>
            
            <%=link_to 'もどる', plans_path, class:"back-btn" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/plans/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>

  <div class="main-top">
    <%= render "main_top" %>
  </div>
</div>

app/views/plans/new.html.erb
<div class="new-expense">
  <div class="new-expense-form">
    <div class="new-expense-top">
      出費の予定を登録する
    </div>

      <div class="new-expense-body">
        <%= form_with model: @plan, local: true do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
          <div class="new-expense-body-name">支払日</div>
          <%= f.date_select :start_time, id:"plan-day" %>

          <div class="new-expense-body-name">名前</div>
          <%= f.text_area :name, class:"expense-text", id:"plan-name", placeholder:"必須：購入した物", maxlength:"40" %>

         <div class="new-expense-body-name">金額</div>
         <span class="sell-yen">¥</span>
         <%= f.text_field :price, class:"price-input", id:"plan-price", placeholder:"必須：半角数字で入力してください" %>

          <div class="new-expense-body-name">支払い方法</div>
          <%= f.collection_select(:payment_id, Payment.all, :id, :name, {}, {class:"select-box", id:"plan-payment"}) %>

          <div class="new-expense-body-name">メモ</div>
          <%= f.text_area :memo, class:"expense-text", id:"plan-memo" %>
 

          <div class="sell-btn-contents">
              <%= f.submit "登録する" ,class:"button-type1" %>
              <%=link_to 'もどる', plans_path, class:"back-btn" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <div class ="calendar-heading-left">
       <%= link_to t('simple_calendar.previous', default: '戻る'), calendar.url_for_previous_view %>
       <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
        <%= link_to t('simple_calendar.next', default: '次へ'), calendar.url_for_next_view %>
    </div>
    <div lass ="calendar-heading-right">
      <div class="button-type2">
        <%= link_to "出費予定を登録", new_plan_path, class: "post" %> 
      </div>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
マイページ
<%= form_with model: current_user, local: true do |f|%>

<%= f.label :nickname%>
<%= f.text_field :nickname, autofocus: true%>

<%= f.label :email%>
<%= f.text_field :email, autofocus: true%>

<%= f.submit "変更する", class: 'btn'%>
<% end %>

<%= link_to "戻る", root_path, class: 'btn'%>